/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as SoldRouteImport } from './routes/sold'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as DevelopmentsIndexRouteImport } from './routes/developments/index'
import { Route as DevelopmentsSlugRouteImport } from './routes/developments/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const SoldRoute = SoldRouteImport.update({
  id: '/sold',
  path: '/sold',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopmentsIndexRoute = DevelopmentsIndexRouteImport.update({
  id: '/developments/',
  path: '/developments/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopmentsSlugRoute = DevelopmentsSlugRouteImport.update({
  id: '/developments/$slug',
  path: '/developments/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/sold': typeof SoldRoute
  '/testimonials': typeof TestimonialsRoute
  '/developments/$slug': typeof DevelopmentsSlugRoute
  '/developments/': typeof DevelopmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/sold': typeof SoldRoute
  '/testimonials': typeof TestimonialsRoute
  '/developments/$slug': typeof DevelopmentsSlugRoute
  '/developments': typeof DevelopmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/sold': typeof SoldRoute
  '/testimonials': typeof TestimonialsRoute
  '/developments/$slug': typeof DevelopmentsSlugRoute
  '/developments/': typeof DevelopmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/sold'
    | '/testimonials'
    | '/developments/$slug'
    | '/developments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/sold'
    | '/testimonials'
    | '/developments/$slug'
    | '/developments'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/sold'
    | '/testimonials'
    | '/developments/$slug'
    | '/developments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  SoldRoute: typeof SoldRoute
  TestimonialsRoute: typeof TestimonialsRoute
  DevelopmentsSlugRoute: typeof DevelopmentsSlugRoute
  DevelopmentsIndexRoute: typeof DevelopmentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sold': {
      id: '/sold'
      path: '/sold'
      fullPath: '/sold'
      preLoaderRoute: typeof SoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developments/': {
      id: '/developments/'
      path: '/developments'
      fullPath: '/developments/'
      preLoaderRoute: typeof DevelopmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developments/$slug': {
      id: '/developments/$slug'
      path: '/developments/$slug'
      fullPath: '/developments/$slug'
      preLoaderRoute: typeof DevelopmentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  SoldRoute: SoldRoute,
  TestimonialsRoute: TestimonialsRoute,
  DevelopmentsSlugRoute: DevelopmentsSlugRoute,
  DevelopmentsIndexRoute: DevelopmentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
